version: '3.8'

services:

  dev:
    build: ./docker/dev
#    user: ${USER_UID:-1000}:${USER_GID:-1000}
    tty: true
    environment:
      - TZ=Europe/Moscow
    ports:
      - ${UI_HOST_PORT:-8000}:8000
